### ISSUE TITLE
correct pvlpy references

### ISSUE THREAD

**Issue by dacoex** [Sandia-Labs/PVLIB_Python#43]
correct the (old?) pvlpy package references

See: the following pull request:
https://github.com/Sandia-Labs/PVLIB_Python/pull/39

See also why necessary:
https://code.launchpad.net/~pythonxy/+archive/ubuntu/pythonxy-devel/+build/6954756/+files/buildlog_ubuntu-vivid-amd64.pvlib_0.3.0~ppa3~revno-75~ubuntu15.04.1_FAILEDTOBUILD.txt.gz

**Comment by Calama-Consulting** [comment]
Merged, thanks for the update!
